### ISSUE TITLE
Servisi kullanmaya yetkiniz yoktur

### ISSUE THREAD

**Issue by kargasa1982** [alpertuna/php-kpsv2-sorgulayici#2]
servis ile adres sorgusu yapmak istiyorum, izin verilen senvislerde KimlikNoSorgulaAdresServis bulunmakta ve kapsanan ilceye ait bir tckimlik ile ve izinli ip adresi sorgu yapıyorum sürekli 8 nolu Servisi kullanmaya yetkiniz yoktur diye uyarı veriyor. kullanıcı adı ve şifre olarak idari tckimlikno ve şifre verildi. Nerede hata yapıyor olabiliriz?

**Comment by alpertuna** [comment]
Sorgu isteğini atan sunucunuzun interente çıkış ipsinin nvi tarafından izinli olması gerekmektedir. Muhtemelen yaşadığınız sorun bununla ilgili.
