### ISSUE TITLE
Sonuç Çıktısı

### ISSUE THREAD

**Issue by ozdemirburakk** [alpertuna/php-kpsv2-sorgulayici#3]
Merhabalar , örnek kod için teşekkürler. Kendi kurum kodum ve şifrem ile veriyi alabiliyorum. Fakat veri string olarak tek değerde dönüyor. Bu konuda yardımcı olabilirseniz çok sevinirim. Aşağıya çıktı linkini bırakıyorum.

[örnek çıktı](https://prnt.sc/1yv6ih3)

**Comment by alpertuna** [comment]
Merhaba,
Veri xml olarak gelmesi gerekiyor, veriyi oldugu gibi html icerisine dump ediyorsaniz ve tarayici ile goruntuluyorsaniz, tarayici xml taglarini goz ardi ettigi icin o sekilde goruyor olabilirsiniz.
Veriyi parse etmek icin [SimpleXMLElement](https://www.php.net/manual/tr/class.simplexmlelement.php) sinifini kullanabilirsiniz.

Baskasinin forkundan ornek: https://github.com/cahitkome/php-kpsv2-sorgulayici/blob/12aedcd0f996e8789151cfb13784fce2c05a80a9/ornek.php#L34

**Comment by ozdemirburakk** [comment]
Verdiğiniz örneği denedim , faydalı oldu hocam elinize sağlık çok teşekkür
ederim

H.Alper Tuna ***@***.***>, 9 Kas 2021 Sal, 17:22 tarihinde
şunu yazdı:

**Comment by alpertuna** [comment]
Sorunun cozulmesine sevindim. Iyi calismalar.
